[package]
name = "modules-and-vectors"
version = "0.1.0"
authors = ["Timothy Merfry Tiwow <s21810014@student.unklab.ac.id>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
